name: modern_slavery
channels:
  - conda-forge
dependencies:
  - ipykernel
  - matplotlib
  - nltk
  - numpy
  - openpyxl
  - pandas
  - pip
  - python
  - requests
  - Pillow
  - seaborn
  - scipy
  - scikit-learn
  - tqdm
  - xlrd
  - pip:
#       - func_timeout
#       - glob3
#       - langdetect
#       - PyPDF2
#       - beautifulsoup4
#       - pytesseract
#       - pdf2image
      - pickle-mixin
#       - stopit
#       - tesseract-ocr
#       - tika
