name: modern_slavery
channels:
  - conda-forge
dependencies:
  - ipykernel
  - numpy
  - pandas
  - xlrd
  - pip
  - python
  - openpyxl
  - requests
  - Pillow
  - pip:
      - func_timeout
      - glob3
      - pickle-mixin
      - PyPDF2
      - langdetect
      - tika
      - beautifulsoup4
#       - pytesseract
      - pdf2image
#       - tesseract-ocr
      - nltk
      - stopit
