name: modern_slavery
channels:
  - conda-forge
dependencies:
  - black
  - bokeh=2.3.0
  - dask-jobqueue=0.7.2
  - ipykernel
  - ipywidgets
  - jupyterlab
  - gensim
  - isort
  - matplotlib
  - nltk
  - numpy
  - openpyxl
  - pandas
  - pip
  - python
  - pylint
  - pycodestyle
  - pydocstyle
  - requests
  - Pillow
  - seaborn
  - scipy
  - scikit-learn
  - tqdm
  - xlrd
  - xlsxwriter
  - pip:
#       - glob3
#       - langdetect
#       - PyPDF2
#       - beautifulsoup4
#       - pytesseract
#       - pdf2image
      - pickle-mixin
      - fuzzywuzzy==0.18.0
      - python-Levenshtein==0.12.2
#       - tesseract-ocr
#       - tika
      - urlextract
