name: modern_slavery
channels:
  - conda-forge
dependencies:
  - black
  - flake8
  - ipykernel
  - ipywidgets
  - jupyterlab
#  - gensim
  - isort
  - matplotlib
  - nltk
  - numpy
  - openpyxl
  - pandas
  - pip
  - python
#  - requests
#  - Pillow
  - seaborn
  - scipy
#  - scikit-learn
#  - wordcloud
  - tqdm
  - xlrd
  - xlsxwriter
  - pip:
    - URLExtract
    # - PyPDF2
    # - beautifulsoup4
    # - pytesseract
    # - pdf2image
    # - modern-slavery-statements-research
    # - pickle-mixin
    # - fuzzywuzzy==0.18.0
    # - python-Levenshtein==0.12.2
    # - tesseract-ocr
    # - tika

